#' Sus scrofa chr18 expression data combining a "bigwig" file and the "bed"
#' annotation file
#'
#'
#' @return A \code{matrix}.
#'
#' @format A \code{gRanges} of the 693 rows of chromosome 18:
#'
#'
#' @source This dataset was generated from ENSEMBL annotation data and
#' a bigwig file generated by nfcore/chipseq
#'
#'
"gRanges_test"
