#' Sus scrofa chr18 expression data combining a "bigwig" file and the "bed"
#' annotation file
#'
#'
#' @return A \code{data.frame}.
#'
#' @format A \code{data.frame} of 24 samples + 4 Tem-methyl and 4 Tem-input
#' with bigwig files after the BayMeth transformation (methylation ratio)
#'
#'
#' @source This dataset was generated from starting data and
#' a bigwig file generated by BayMeth method
#'
#'
"list_file"
